name: Docker

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          target: "prod"
          platforms: linux/amd64,linux/arm64
          provenance: false
          tags: ghcr.io/deanpcmad/buildtea:commit-${{ github.sha }},ghcr.io/deanpcmad/caddy-cloudflare-docker:latest
