name: Docker

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          provenance: false
          tags: ghcr.io/deanpcmad/caddy-cloudflare-docker:commit-${{ github.sha }},ghcr.io/deanpcmad/caddy-cloudflare-docker:latest
